name: Build pioneos-oobe

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: sudo apt update
    
    - run: sudo apt upgrade -y

    - run: make dist

    - uses: actions/upload-artifact@v4
      with:
        name: pioneos-oobe
        path: *.deb